# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MacroManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MacroManager
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'AlamofireImage'

  target 'MacroManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MacroManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
